services:
  - type: web
    name: clickhome-site
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start -- -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
